name: Release Build

on:
  push:
    tags:
      - 'v*'  # Trigger on semantic version tags (e.g. v1.0.0)

jobs:
  build-and-release:
    runs-on: windows-latest
    env:
      SOLUTION_DIR: ${{ github.workspace }}
      WIX_PATH: 'C:\Program Files (x86)\WiX Toolset v3.14\bin'

    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Verify WiX Installation
      run: |
        echo "WIX_PATH: $env:WIX_PATH"
        & "$env:WIX_PATH\heat.exe" -?  # Use correct help syntax

    - name: Build fmt library
      run: |
       cd deps/fmt
       mkdir build && cd build
       cmake .. -DFMT_TEST=OFF -DCMAKE_CXX_FLAGS="/W3"  # Disable tests & reduce warning level
       cmake --build . --config Release

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: nuget restore PowerToys.sln


    - name: Build Solution (Release x64)
      run: msbuild PowerToys.sln /p:Configuration=Release /p:Platform=x64 /p:RestorePackages=false /p:AdditionalOptions="/utf-8 /I$(Build.SourcesDirectory)\deps\fmt\include"

    - name: Build Prerequisite Tools
      run: |
        msbuild tools\BugReportTool\BugReportTool.sln /p:Configuration=Release /p:Platform=x64
        msbuild tools\StylesReportTool\StylesReportTool.sln /p:Configuration=Release /p:Platform=x64

    - name: Build Installer
      run: msbuild installer\PowerToysSetup.sln /p:Configuration=Release /p:Platform=x64

    - name: Collect Artifacts
      run: |
        mkdir artifacts
        copy "installer\PowerToysSetup\x64\Release\PowerToysSetup.msi" artifacts\
        copy "installer\PowerToysSetup\x64\Release\PowerToysSetup.exe" artifacts\

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-binaries
        path: artifacts/**
        retention-days: 7

  release:
    needs: build-and-release
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: release-binaries
        path: ./artifacts

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload MSI Installer
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/PowerToysSetup.msi
        asset_name: PowerToysSetup-${{ github.ref }}.msi
        asset_content_type: application/octet-stream

    - name: Upload EXE Installer
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/PowerToysSetup.exe
        asset_name: PowerToysSetup-${{ github.ref }}.exe
        asset_content_type: application/octet-stream