name: Create Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  build:
    name: Create Release
    runs-on: windows-latest # Using Windows runner since PowerToys is a Windows application
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x' # Adjust version as needed
          
      - name: Restore NuGet packages
        run: |
          dotnet restore PowerToys.sln
          msbuild -t:restore PowerToys.sln
          
      - name: Build
        run: |
          msbuild PowerToys.sln /p:Configuration=Release /p:Platform=x64

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            ./x64/Release/*.exe
            ./x64/Release/*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
